version: "3.9"  # optional since v1.27.0
services:
  api: 
    build:
        context: ./API/WebApi_Cadastro
        dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
  dbData: 
    image: mcr.microsoft.com/mssql/server:2019-latest
    entrypoint: /bin/bash
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Intelitrader2022
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "7000:1433"
    volumes:
      - /var/opt/mssql
      
      - ./:/usr/src/app 
    
    working_dir: /usr/src/app 
    
    command: sh -c ' chmod +x ./entrypoint.sh; ./entrypoint.sh & /opt/mssql/bin/sqlservr;'
    volumes_from:
      - dbData